/* ============================================================
   EXPORT — js/modules/export.js
   Generates a JPEG of the shortlist using html2canvas.
   Builds a self-contained off-screen element for a clean render.
   ============================================================ */

import { typeLabel, formatDuration } from './ui.js';
import { getSavedLocations } from './shortlist.js';

/* ---------------------------------------------------------- */

export function initExport() {
  document.getElementById('export-btn')
    ?.addEventListener('click', exportShortlist);
}

async function exportShortlist() {
  const exportBtn = document.getElementById('export-btn');
  const spinner   = document.getElementById('export-spinner');

  exportBtn.hidden = true;
  if (spinner) spinner.hidden = false;

  try {
    const saved = getSavedLocations();

    if (saved.length === 0) {
      alert('Add some locations to your shortlist first.');
      return;
    }

    const el = buildExportElement(saved);
    document.body.appendChild(el);

    const canvas = await html2canvas(el, {
      backgroundColor: '#161616',
      scale:            2,
      useCORS:          true,
      logging:          false,
    });

    document.body.removeChild(el);

    const date = new Date().toISOString().slice(0, 10);
    const link = document.createElement('a');
    link.download = `slowecho-shortlist-${date}.jpg`;
    link.href     = canvas.toDataURL('image/jpeg', 0.92);
    link.click();

  } catch (err) {
    console.error('[export] Failed:', err);
    alert('Export failed — please try again.');
  } finally {
    exportBtn.hidden = false;
    if (spinner) spinner.hidden = true;
  }
}

/* --- Off-screen export element ----------------------------- */

function buildExportElement(saved) {
  const totalMin  = saved.reduce((sum, l) => sum + l.duration, 0);
  const totalStr  = formatDuration(totalMin);
  const date      = new Date().toLocaleDateString('en-GB', {
    day: 'numeric', month: 'long', year: 'numeric',
  });

  // Inline styles so html2canvas doesn't need to resolve CSS variables
  const el = document.createElement('div');
  el.style.cssText = [
    'position:fixed',
    'left:-9999px',
    'top:0',
    'width:520px',
    'background:#161616',
    'color:#efefef',
    'font-family:Georgia,"Times New Roman",serif',
    'padding:40px',
    'border-radius:0',
  ].join(';');

  const rows = saved.map(loc => `
    <tr>
      <td style="padding:12px 0;border-bottom:1px solid #2b2b2b;vertical-align:top;">
        <div style="font-size:15px;font-weight:500;margin-bottom:3px;font-family:Georgia,serif;">
          ${loc.name}
        </div>
        <div style="font-size:12px;color:#888;font-family:system-ui,sans-serif;">
          ${typeLabel(loc.type)} &nbsp;·&nbsp; ${loc.bestTime}
        </div>
        <div style="font-size:12px;color:#888;font-family:system-ui,sans-serif;margin-top:2px;">
          ${loc.openingTimes}
        </div>
      </td>
      <td style="padding:12px 0 12px 24px;border-bottom:1px solid #2b2b2b;
                 vertical-align:top;text-align:right;white-space:nowrap;">
        <div style="font-size:14px;font-family:system-ui,sans-serif;">~${loc.duration} min</div>
        <div style="font-size:12px;color:#888;font-family:system-ui,sans-serif;margin-top:2px;">
          ${loc.traffic} traffic
        </div>
      </td>
    </tr>
  `).join('');

  el.innerHTML = `
    <!-- Header -->
    <div style="display:flex;align-items:flex-end;justify-content:space-between;
                margin-bottom:28px;padding-bottom:16px;border-bottom:1px solid #2b2b2b;">
      <div>
        <div style="font-size:22px;letter-spacing:0.04em;">Studio Slowecho</div>
        <div style="font-size:13px;color:#888;margin-top:4px;
                    font-family:system-ui,sans-serif;">Edinburgh Shoot Planner</div>
      </div>
      <div style="font-size:12px;color:#666;font-family:system-ui,sans-serif;">${date}</div>
    </div>

    <!-- Location rows -->
    <table style="width:100%;border-collapse:collapse;">
      <tbody>${rows}</tbody>
    </table>

    <!-- Total -->
    <div style="display:flex;align-items:center;justify-content:space-between;
                margin-top:20px;padding-top:16px;">
      <div style="font-size:13px;color:#888;font-family:system-ui,sans-serif;">
        Total estimated shoot time
      </div>
      <div style="font-size:22px;color:#c8a96e;">${totalStr}</div>
    </div>

    <!-- Footer -->
    <div style="margin-top:32px;text-align:center;font-size:11px;color:#444;
                font-family:system-ui,sans-serif;letter-spacing:0.04em;">
      Generated by Studio Slowecho
    </div>
  `;

  return el;
}
